### ISSUE TITLE
Extension not works in VSCode 1.102.0

### ISSUE THREAD

**Issue by d0sse** [be5invis/vscode-custom-css#264]
# vscode-custom-css not working on macOS 15.5 (M2 Pro)

## 🐞 Issue Summary

On macOS 15.5 (M2 Pro), the extension `vscode-custom-css` fails to function with the following error:

## 💻 Environment

- **macOS Version:** 15.5 (Darwin arm64 24.5.0)
- **Chip:** Apple M2 Pro
- **VSCode Version:**  
  - Version: `1.102.0`  
  - Commit: `cb0c47c0cfaad0757385834bd89d410c78a856c0`  
  - Date: `2025-07-09T22:10:34.600Z`  
  - Electron: `35.6.0`  
  - Chromium: `134.0.6998.205`  
  - Node.js: `22.15.1`  
  - V8: `13.4.114.21-electron.0`

## ⚠️ Error Output
`Unable to locate the installation path of VSCode. This extension may not function correctly.
Source: Custom CSS and JS Loader`

## 🌄 Screenshot:

<img width="471" height="119" alt="Image" src="https://github.com/user-attachments/assets/bf6a7c8f-1b13-4af9-a6a7-9229fb314ffc" />

**Comment by Tostti** [comment]
Same error here.
 
Also got this error if I try to run the enable command 

<img width="522" height="71" alt="Image" src="https://github.com/user-attachments/assets/bfb45bea-f29e-456e-878b-f727b40aa88c" />

## Environment: 
- Manjaro Linux
- Kernel: 6.12.34-1
- VSCode: 
  - Version: `1.102.0`
  - Commit: `cb0c47c0cfaad0757385834bd89d410c78a856c0`

**Comment by MrBns** [comment]
Same here.. Not working for me also.
- Ubuntu
- Vscode `1.102.0`

**Comment by wxmup** [comment]
me, too.
- Arch Linux
- VS Code `1.102.0`
- error: `Unable to locate the installation path of VSCode. This extension may not function correctly.`

**Comment by moalamri** [comment]
https://github.com/BartaG512/custom-css-hot-reload/issues/4#issuecomment-3064703327

**Comment by be5invis** [comment]
It should already be fixed by #262.

**Comment by be5invis** [comment]
Or is Macintosh/Linux having a different locatiln of the main HTML file?

**Comment by voodoobox** [comment]
Still not working. Any logs on information that might help narrowing down the issue?

**Comment by be5invis** [comment]
There’s no `workbench` in the path? Please show the full path to `workbench.html`.

**Comment by voodoobox** [comment]
<img width="1140" height="653" alt="Image" src="https://github.com/user-attachments/assets/a50e15a1-4621-4ed6-8aa2-fe8a7776676e" />

<img width="1140" height="653" alt="Image" src="https://github.com/user-attachments/assets/fc2cfe5b-117d-42ec-940a-8840532a7089" />

**Comment by voodoobox** [comment]
I copied the worckbench.html in electron-sandbox to electron-browser and it worked.

**Comment by d0sse** [comment]
> v7.4.6 should have a better fix

Thanks v7.4.6 works!

**Comment by The-Compiler** [comment]
Can confirm things work again for me on Archlinux with v7.4.6 too! 🎉
